--------------------------------------------------------------------------------
-- Copyright © 2021+ Eamonn Anthony Duffy. All Rights Reserved.
--------------------------------------------------------------------------------
--
-- Version: V1.0.0.
--
-- Created: Eamonn A. Duffy, 2-May-2021.
--
-- Updated: Eamonn A. Duffy, 11-August-2026.
--
-- Purpose: Forward Script for the Main Sql for the Rapture Therapy Database.
--
-- Target: PostgreSQL.
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Create Schema and Table.
--------------------------------------------------------------------------------

BEGIN TRANSACTION;

CREATE SCHEMA IF NOT EXISTS "Dad";

CREATE TABLE IF NOT EXISTS "Dad"."RaptureTherapyDatabaseVersions"
(
    "DatabaseVersionId"      Int NOT NULL CONSTRAINT "PK_Dad_RaptureTherapyDatabaseVersions" GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    "Major"                  Int NOT NULL,
    "Minor"                  Int NOT NULL,
    "Patch"                  Int NOT NULL,
    "Build"                  VarChar(128) NOT NULL,
    "Description"            VarChar(256) NOT NULL,
    "CreatedDateTimeUtc"     TimeStampTz NOT NULL CONSTRAINT "DF_Dad_RaptureTherapyDatabaseVersions_CreatedDateTimeUtc" DEFAULT (CLOCK_TIMESTAMP() AT TIME ZONE 'UTC'),
    "LastUpdatedDateTimeUtc" TimeStampTz NULL,

    CONSTRAINT "UX_Dad_RaptureTherapyDatabaseVersions_Version" UNIQUE ("Major", "Minor", "Patch", "Build")
);

INSERT INTO "Dad"."RaptureTherapyDatabaseVersions"
    ("Major", "Minor", "Patch", "Build", "Description")
SELECT 1, 0, 0, '0', 'Beta Build.' WHERE NOT EXISTS (
    SELECT 1
    FROM "Dad"."RaptureTherapyDatabaseVersions"
    WHERE "Major" = 1
      AND "Minor" = 0
      AND "Patch" = 0
      AND "Build" = '0'
);

COMMIT TRANSACTION;

--------------------------------------------------------------------------------
-- End Of File.
--------------------------------------------------------------------------------

/*

ROLLBACK TRANSACTION;

*/
